@WebApplication1_HostAddress = http://localhost:5231

GET {{WebApplication1_HostAddress}}/todos


###
POST {{WebApplication1_HostAddress}}/todos
content-type: application/json
{
  "id": 1,
  "name": "todo1",
  "isComplete": false
}

###
GET {{WebApplication1_HostAddress}}/todos/1

###
DELETE {{WebApplication1_HostAddress}}/todos/1

###
GET {{WebApplication1_HostAddress}}/tasks/1

###
POST {{WebApplication1_HostAddress}}/tasks